name: osm_search_and_pick
description: A flutter place search and location picker plugin that uses Open Street Map.
version: 0.1.1
homepage: https://github.com/mrmhthegreat/osm_search_and_pick.git

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  http: ^1.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
